name: Robô Diário de Licitações

on:
  schedule:
    # Dispara às 23:51 (Horário de Brasília) / 02:51 UTC
    - cron: '51 2 * * *'
  workflow_dispatch:

jobs:
  executar-script:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.
