name: Robo Extrator TCM-PA

on:
  schedule:
    # 23:23 de Brasília equivale a 02:23 UTC do dia seguinte
    - cron: '23 2 * * *'
  workflow_dispatch: # Permite testar e rodar o robô manualmente na aba Actions do GitHub

jobs:
  run-scraping:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar bibliotecas necessárias
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas google-api-python-client google-auth

    - name: Executar Robô de Raspagem
      env:
        GOOGLE_DRIVE_JSON: ${{ secrets.GOOGLE_DRIVE_JSON }}
      run: |
        python main.py
